name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: deps
      run: sudo apt-get install gettext libsidplayfp-dev libmpg123-dev
    - uses: actions/checkout@v2
    - name: bootstrap
      run: |
        mkdir build-aux
        touch build-aux/config.rpath
        autoreconf -vfi
    - name: configure
      run: ./configure
    - name: make distcheck
      run: make distcheck
